Login, Registration and some css
dzikus13/league pull request #46
Opened 2022-05-25 07:42 UTC by REV3NSS

Added Login, Registration and some css.

2022-05-25 12:42 UTC, rs-piotr-kryska requested changes
Please do no push pyc files (and db.sqlite)

2022-05-25 12:43 UTC, rs-piotr-kryska commented on league/manager/forms.py
> +		return user
Its strangethat it is necessary

2022-05-25 12:44 UTC, rs-piotr-kryska commented on league/manager/migrations/0003_alter_league_max_number_of_teams.py
> +    ]
Please remove migrations

2022-05-27 07:16 UTC, Shefour commented
@skam34 can you look at this

2022-05-31 07:12 UTC, closed without merging